import prismaClient from "./utils/connector.ts";

const characterAbilities = [
  {
    name: "Shadow Clone Jutsu",
    description: "A high-level ninjutsu that allows the user to create multiple clones of themselves, each capable of independent action and combat.",
  },
  {
    name: "Rasengan",
    description: "A powerful spinning ball of chakra that is compact and destructive, developed by the Fourth Hokage, Minato Namikaze.",
  },
  {
    name: "Chidori",
    description: "A high-speed thrust of concentrated lightning chakra, designed for assassination and developed by Kakashi Hatake.",
  },
  {
    name: "Amaterasu",
    description: "Black flames that burn anything in their path, generated by the Mangekyo Sharingan. They cannot be extinguished until the target is completely destroyed.",
  },
  {
    name: "Susanoo",
    description: "A massive, humanoid avatar made of chakra, used by Uchiha clan members with Mangekyo Sharingan. It provides immense offensive and defensive capabilities.",
  },
  {
    name: "Sage Mode",
    description: "A state that enhances the user's physical strength, sensory perception, and chakra control by absorbing natural energy.",
  },
  {
    name: "Byakugan",
    description: "A Kekkei Genkai of the Hyuga clan, granting near-360-degree vision and the ability to see chakra flow within the body.",
  },
  {
    name: "Rinnegan",
    description: "The ultimate Dojutsu, allowing mastery over all chakra natures and granting unique abilities such as the Six Paths Techniques.",
  },
  {
    name: "Eight Gates",
    description: "A forbidden taijutsu technique that unlocks the body's chakra gates, granting immense strength and speed at the cost of severe physical strain.",
  },
  {
    name: "Wood Release",
    description: "A rare Kekkei Genkai that combines earth and water chakra to create and manipulate wood for combat and construction.",
  },
  {
    name: "Healing Jutsu",
    description: "Medical ninjutsu that allows the user to heal physical injuries by focusing and channeling chakra into the affected area.",
  },
  {
    name: "Flying Thunder God Technique",
    description: "A space-time ninjutsu that allows instantaneous teleportation to a marked location, developed by the Second Hokage and perfected by the Fourth Hokage.",
  },
  {
    name: "Tailed Beast Bomb",
    description: "A devastating attack used by tailed beasts, where a massive amount of chakra is condensed into a sphere and fired as a destructive beam.",
  },
  {
    name: "Sharingan",
    description: "A Dojutsu of the Uchiha clan that enhances perception, grants copying abilities, and allows powerful genjutsu manipulation.",
  },
  {
    name: "Edo Tensei",
    description: "A forbidden summoning jutsu that resurrects the dead to serve the caster while retaining their original abilities and memories.",
  },
];

  characterAbilities.forEach(async (ability) => {
    await prismaClient.abilities.create({
        data: ability
    })
  })