### GET All Characters
GET http://localhost:3001/api/animes/65a7fe92-16c9-4a81-945b-14a43a468758/characters

### Get Character by ID
GET http://localhost:3000/api/animes/65a7fe92-16c9-4a81-945b-14a43a468758/characters/051cac5f-b64e-477c-82c8-9ce6e8219dd8

### POST Character
POST http://localhost:3001/api/animes/76f451ba-ef02-4488-9f93-a56ad40e7015/characters
Content-Type: application/json

{
  "thumbnail": "https://example.com/thumbnails/hisoka-morow.jpg",
  "name": "Hisoka Morow",
  "description": "Hisoka es un misterioso y carismático usuario de Nen que mezcla un comportamiento excéntrico con habilidades mortales. Conocido por su obsesión con los combates fuertes, a menudo actúa como antagonista y aliado según sus intereses.",
  "origin": "Desconocido",
  "birthDate": "Desconocida",
  "age": "27 años (aproximadamente)",
  "role": "Antagonista y cazador profesional",
  "personality": "Hisoka es impredecible, hedonista y manipulador. Disfruta del caos y las peleas intensas, mostrando interés en personajes con gran potencial como Gon y Killua. Su naturaleza retorcida lo hace tan intrigante como aterrador.",
  "background": "Antes de los eventos principales, Hisoka se unió al Examen de Cazador y lo aprobó, destacándose por su gran dominio de Nen. También fue un miembro temporal de la Brigada Fantasma, aunque su lealtad siempre ha sido hacia su propio entretenimiento.",
  "bio": "Durante la historia, Hisoka desafía y mide las habilidades de Gon, Killua y otros personajes clave. Utiliza su habilidad Nen 'Bungee Gum' para crear estrategias versátiles y devastadoras en combate. Su motivación principal es encontrar rivales que lo exciten en combate.",
  "abilities": []
}


###




###
